networks:
  hoodi:
    rpc_url: "https://rpc.hoodi.ethpandaops.io"
    dora_url: "https://dora.hoodi.ethpandaops.io"
    wallet_privkey: "$BLOATER_PRIVKEY"
    validator_mnemonic: "$BLOATER_MNEMONIC"
    storage_seed: "01"
    deposit_contract: "0x00000000219ab540356cBB839Cbe05303d7705Fa"
    withdrawal_request_contract: "0x00000961Ef480Eb55e80D19ad83579A64c007002"
    operations:
      deposits:
        enabled: true
        #per_day_limit: 2400
        #max_queue_size: 600
        per_day_limit: 1600
        max_queue_size: 400
        total_count: 1000000
        deposit_amount: 1000000000
        batch_size: 40
        storage_update_interval: 50
      withdrawal_requests:
        enabled: false
        per_day_limit: 50
        max_queue_size: 200
        total_count: 5000
        withdraw_amount: 1 # gwei, 0 = full withdrawal (exit)
        batch_size: 16
        storage_update_interval: 50
